var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/garden/fee-groups/route.js")
R.c("server/chunks/[root-of-the-server]__0k075is._.js")
R.c("server/chunks/_0t-.sc9._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/_next-internal_server_app_api_garden_fee-groups_route_actions_0wlg~4f.js")
R.m(713233)
module.exports=R.m(713233).exports
