var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/security/trusted-device/route.js")
R.c("server/chunks/_0t-.sc9._.js")
R.c("server/chunks/[root-of-the-server]__0ll1lzz._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/_next-internal_server_app_api_security_trusted-device_route_actions_0~os0dh.js")
R.m(339674)
module.exports=R.m(339674).exports
