import Link from "next/link";
import { Check, ShieldCheck } from "lucide-react";
import { ObserverMark } from "@/components/digital-observer/observer-app-shell";
import { createClient } from "@/lib/supabase/server";

async function loadPackages() { try { const supabase = await createClient(); const result = await supabase.from("observer_monitoring_packages" as any).select("id,name,package_key,package_type,camera_limit,site_limit,user_limit,recording_retention_hours,monthly_price,annual_price,annual_discount_percent,alert_channels,human_review_required,support_tier,active,sort_order").eq("active",true).order("sort_order"); return result.error ? [] : result.data ?? []; } catch { return []; } }

export default async function DigitalObserverPricingPage() {
  const packages = await loadPackages();
  return <main className="do-public do-pricing-page" dir="rtl"><header className="do-public-header"><Link className="do-auth-brand dark" href="/digital-observer"><ObserverMark /><span><b>תצפיתן דיגיטלי</b><small>חבילות גמישות מהאדמין</small></span></Link><nav><Link href="/digital-observer">המוצר</Link><Link href="/digital-observer/trust">פרטיות ואמון</Link></nav><div><Link className="do-button secondary" href="/digital-observer/login">התחברות</Link></div></header><section className="do-pricing-head"><span className="do-badge info">ללא חיוב בסביבת הדמו</span><h1>חבילה שמתאימה למספר המצלמות ולמקום שלכם</h1><p>כל המחירים והגבולות מגיעים ממסד הנתונים וניתנים לשינוי באדמין. חיוב אמיתי דורש ספק מאושר.</p></section>{packages.length ? <section className="do-plan-grid public">{packages.map((item: any) => <article className="do-plan" key={item.id}><span>{item.package_type === "home" ? "לבית" : item.package_type === "business" ? "לעסק" : "מותאם"}</span><h2>{item.name}</h2><strong>{item.monthly_price ? `${Number(item.monthly_price).toLocaleString("he-IL")} ₪` : "בהתאמה"}<small> / חודש</small></strong><ul><li><Check /> עד {item.camera_limit ?? "לפי הסכם"} מצלמות</li><li><Check /> עד {item.site_limit ?? "לפי הסכם"} אתרים</li><li><Check /> עד {item.user_limit ?? "לפי הסכם"} משתמשים</li><li><Check /> מקטעי אירוע עד {item.recording_retention_hours ?? 0} שעות</li><li><Check /> ביקורת אנושית {item.human_review_required ? "חובה" : "בהגדרה"}</li></ul><Link className="do-button primary full" href={`/digital-observer/register?type=${item.package_type === "home" ? "home" : "business"}`}>בחירת מסלול</Link></article>)}</section> : <section className="do-empty"><ShieldCheck /><strong>החבילות ממתינות למיגרציה</strong><span>לא מוצגים מחירים קשיחים כתחליף לנתוני האדמין.</span></section>}<div className="do-notice info pricing"><ShieldCheck /><span>השרת הוא מקור האמת למנוי ולהרשאות החבילה. Apple, Google ותשלום אשראי יתחברו דרך מתאם חיוב נפרד.</span></div></main>;
}
