var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/camera-gateway/route.js")
R.c("server/chunks/_0t-.sc9._.js")
R.c("server/chunks/lib_domain_0exyiy6._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/[root-of-the-server]__0ur9_32._.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_camera-gateway_route_actions_0o26dd7.js")
R.m(107857)
module.exports=R.m(107857).exports
