var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/parent-portal/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__11w-02.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_013b.ps.js")
R.c("server/chunks/ssr/[root-of-the-server]__105-.f-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0s6k5ln._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_0zv0b3p.js")
R.c("server/chunks/ssr/_08dqex3._.js")
R.c("server/chunks/ssr/_0zd8-m5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_parent-portal_page_actions_0~2plxn.js")
R.m(53799)
module.exports=R.m(53799).exports
