var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/parent/profile/route.js")
R.c("server/chunks/[root-of-the-server]__0y55pyb._.js")
R.c("server/chunks/_0t-.sc9._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/lib_validation_ts_0nz0al8._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/[root-of-the-server]__0wj1suk._.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/_next-internal_server_app_api_parent_profile_route_actions_0xt1q_c.js")
R.m(652574)
module.exports=R.m(652574).exports
