var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/camera-streams/[id]/view-logs/route.js")
R.c("server/chunks/[root-of-the-server]__0-zxxhe._.js")
R.c("server/chunks/_0t-.sc9._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0t95ft_._.js")
R.c("server/chunks/0zjb_server_app_api_camera-streams_[id]_view-logs_route_actions_0b~lauv.js")
R.m(390369)
module.exports=R.m(390369).exports
