var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/safety-standard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e6dv54._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0nbjmk7.js")
R.c("server/chunks/ssr/[root-of-the-server]__105-.f-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0s6k5ln._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_0zv0b3p.js")
R.c("server/chunks/ssr/_08dqex3._.js")
R.c("server/chunks/ssr/_0zd8-m5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_safety-standard_page_actions_0~wcm8q.js")
R.m(274810)
module.exports=R.m(274810).exports
