var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/policies/required/route.js")
R.c("server/chunks/[root-of-the-server]__0_0e6gd._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/_0t-.sc9._.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/_next-internal_server_app_api_policies_required_route_actions_0uuhvu_.js")
R.m(491959)
module.exports=R.m(491959).exports
