var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/digital-observer/events/review/route.js")
R.c("server/chunks/[root-of-the-server]__08t.sar._.js")
R.c("server/chunks/_0t-.sc9._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/0zjb_server_app_api_digital-observer_events_review_route_actions_0wx1jc-.js")
R.m(902700)
module.exports=R.m(902700).exports
