var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/dashboard/interaction-summary/route.js")
R.c("server/chunks/[root-of-the-server]__00_xz6t._.js")
R.c("server/chunks/_0t-.sc9._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0vcwsgg.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/0zjb_server_app_api_dashboard_interaction-summary_route_actions_0nsk.5u.js")
R.m(561720)
module.exports=R.m(561720).exports
