var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/observe/route.js")
R.c("server/chunks/[root-of-the-server]__02-7c5j._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_observe_route_actions_0snmlfc.js")
R.m(324114)
module.exports=R.m(324114).exports
