var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/medicine-given-logs/route.js")
R.c("server/chunks/_0t-.sc9._.js")
R.c("server/chunks/[root-of-the-server]__01xy9wh._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/[root-of-the-server]__0t95ft_._.js")
R.c("server/chunks/_next-internal_server_app_api_medicine-given-logs_route_actions_00-vk4m.js")
R.m(761060)
module.exports=R.m(761060).exports
