var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/app/register/staff/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rllv5c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0bto-.p.js")
R.c("server/chunks/ssr/_0-b6zpn._.js")
R.c("server/chunks/ssr/[root-of-the-server]__105-.f-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0s6k5ln._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_0zv0b3p.js")
R.c("server/chunks/ssr/_08dqex3._.js")
R.c("server/chunks/ssr/_0zd8-m5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_app_register_staff_page_actions_10k-qwp.js")
R.m(50960)
module.exports=R.m(50960).exports
