var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/tasks/[id]/view/route.js")
R.c("server/chunks/[root-of-the-server]__08i-_xi._.js")
R.c("server/chunks/_0t-.sc9._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0t95ft_._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/_next-internal_server_app_api_tasks_[id]_view_route_actions_10mwpvr.js")
R.m(571179)
module.exports=R.m(571179).exports
