var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/service-charter/route.js")
R.c("server/chunks/[root-of-the-server]__0kwt9ar._.js")
R.c("server/chunks/_0t-.sc9._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/node_modules_next_0vr6dev._.js")
R.c("server/chunks/node_modules_next_0je0vb~._.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/[root-of-the-server]__0vkq1iz._.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_service-charter_route_actions_0wcjquz.js")
R.m(417063)
module.exports=R.m(417063).exports
