var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/parent/additional-child-request/route.js")
R.c("server/chunks/_0t-.sc9._.js")
R.c("server/chunks/[root-of-the-server]__0~_m4e8._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0gyvpql.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_0oyba0e._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_131y~ke.js")
R.c("server/chunks/_0fwqa_u._.js")
R.c("server/chunks/0zjb_server_app_api_parent_additional-child-request_route_actions_0e3oqm1.js")
R.m(654159)
module.exports=R.m(654159).exports
